version: '3'
services:
 db:
   image: mysql:8.0
   command: --default-authentication-plugin=mysql_native_password
   env_file: db.env
   ports:
     - "3306:3306"
   volumes:
     - mysql_data:/var/lib/mysql
 web:
   build:
     context: .
     dockerfile: docker/api/Dockerfile_develop
   command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   env_file: db.env
   volumes:
     - ./src:/myapp
   ports:
     - "3000:3000"
   depends_on:
     - db
 nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile_develop
    volumes:
      - ../src:/myapp
    ports:
      - 8080:80
    depends_on:
      - web
volumes:
  mysql_data:
