version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -e production -C config/puma.rb"
    env_file: db.env
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./src:/myapp
    ports:
      - 8080:80
    depends_on:
      - web
volumes:
  mysql_data:
